package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"nexus/internal/manager/graph/model"
)

// CreateDestination is the resolver for the createDestination field.
func (r *mutationResolver) CreateDestination(ctx context.Context, input model.NewDestination) (*model.DestinationConfig, error) {
	r.Resolver.mu.Lock()
	defer r.Resolver.mu.Unlock()

	id := fmt.Sprintf("dest-%d", len(r.Resolver.Destinations)+1)
	newDest := &model.DestinationConfig{
		ID:      id,
		Name:    input.Name,
		Type:    input.Type,
		URL:     input.URL,
		Enabled: true,
	}
	r.Resolver.Destinations = append(r.Resolver.Destinations, newDest)
	return newDest, nil
}

// ToggleDestination is the resolver for the toggleDestination field.
func (r *mutationResolver) ToggleDestination(ctx context.Context, id string, enabled bool) (*model.DestinationConfig, error) {
	r.Resolver.mu.Lock()
	defer r.Resolver.mu.Unlock()

	for _, d := range r.Resolver.Destinations {
		if d.ID == id {
			d.Enabled = enabled
			return d, nil
		}
	}
	return nil, fmt.Errorf("destination not found")
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context) ([]*model.Agent, error) {
	r.Resolver.mu.RLock()
	defer r.Resolver.mu.RUnlock()
	return r.Resolver.Agents, nil
}

// Destinations is the resolver for the destinations field.
func (r *queryResolver) Destinations(ctx context.Context) ([]*model.DestinationConfig, error) {
	r.Resolver.mu.RLock()
	defer r.Resolver.mu.RUnlock()
	return r.Resolver.Destinations, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
