// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Agent struct {
	ID       string `json:"id"`
	Hostname string `json:"hostname"`
	LastSeen string `json:"lastSeen"`
	Version  string `json:"version"`
	Status   string `json:"status"`
}

type DestinationConfig struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Type    string `json:"type"`
	URL     string `json:"url"`
	Enabled bool   `json:"enabled"`
}

type Mutation struct {
}

type NewDestination struct {
	Name    string  `json:"name"`
	Type    string  `json:"type"`
	URL     string  `json:"url"`
	Headers *string `json:"headers,omitempty"`
}

type Query struct {
}
